{"name": "Test that always fails", "status": "failed", "statusDetails": {"message": "AssertionError: Intentional failure\nassert False", "trace": "@allure.title(\"Test that always fails\")\n    @allure.description(\"This test is supposed to fail for demonstration.\")\n    def test_fail():\n>       assert False, \"Intentional failure\"\nE       AssertionError: Intentional failure\nE       assert False\n\ntests/test_sample.py:11: AssertionError"}, "description": "This test is supposed to fail for demonstration.", "start": 1749163444367, "stop": 1749163444367, "uuid": "14574501-4aeb-4541-a613-23d5b769e7fd", "historyId": "13b46310663651660204086cd193b314", "testCaseId": "13b46310663651660204086cd193b314", "fullName": "tests.test_sample#test_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_sample"}, {"name": "host", "value": "pkrvmf6wy0o8zjz"}, {"name": "thread", "value": "2106-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_sample"}]}